name: Train and Build ONNX

on:
  workflow_dispatch:
  push:
    paths:
      - requirements.txt
      - train_oxnet.py
      - gen_synth_dataset.py
      - .github/workflows/train.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate synthetic dataset
        run: |
          python gen_synth_dataset.py --out dataset --train 4000 --val 800 --img-size 28

      - name: Train and export ONNX model
        run: |
          python train_oxnet.py --data dataset --epochs 8 --batch 128 --onnx model/model.onnx

      - name: Upload ONNX artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-onnx
          path: model/model.onnx